(() => {
  'use strict';
  const lessons = [
    {
      id: 'foundation',
      number: '00',
      title: '共同基础：一次反弹',
      file: 'gi_module_foundations.html',
      group: 'base',
      prerequisites: [],
      stages: 6,
      summary: '从距离、余弦、Lambert 与采样权重逐步组装一次漫反射反弹。',
    },
    {
      id: 'rsm',
      number: '01',
      title: 'RSM：采样、瑕疵与修复',
      file: 'gi_module_rsm.html',
      group: 'screen',
      prerequisites: ['foundation'],
      stages: 9,
      summary: '从光源 MRT 到 VPL gather，并实际比较 raw、空间滤波、时序累积与错误可见性。',
    },
    {
      id: 'ssgi',
      number: '02',
      title: 'SSAO / SSGI',
      file: 'gi_module_ssao_ssgi.html',
      group: 'screen',
      prerequisites: ['foundation'],
      stages: 7,
      summary: '拆开深度重建、射线投影、命中、辐射回收、空间滤波和 history validation。',
    },
    {
      id: 'sh',
      number: '03',
      title: 'Spherical Harmonics',
      file: 'gi_module_sh.html',
      group: 'direction',
      prerequisites: ['foundation'],
      stages: 8,
      summary: '从九个系数到卷积、旋转、band 不变量、ringing 与 Probe/PRT 应用。',
    },
    {
      id: 'voxel',
      number: '04',
      title: 'Voxelization',
      file: 'gi_module_voxelization.html',
      group: 'volume',
      prerequisites: ['foundation'],
      stages: 7,
      summary: '世界坐标映射、保守写入、材质合并、明确光源注入与 level-0 volume。',
    },
    {
      id: 'cone',
      number: '05',
      title: 'Voxel Cone Tracing',
      file: 'gi_module_cone_tracing.html',
      group: 'volume',
      prerequisites: ['voxel'],
      stages: 7,
      summary: '消费 Voxel 输出，逐步解释 mip、footprint、累计、diffuse/specular cones。',
    },
    {
      id: 'probes',
      number: '06',
      title: 'Irradiance Probe 基础',
      file: 'gi_module_probes.html',
      group: 'direction',
      prerequisites: ['sh'],
      stages: 5,
      summary: '先把插值、漏光、visibility 与缓存过期讲清，再进入 DDGI teaching-lite 组装。',
    },
    {
      id: 'prt',
      number: '07',
      title: 'PRT / Transfer Probes',
      file: 'gi_module_prt_probes.html',
      group: 'direction',
      prerequisites: ['sh', 'probes'],
      stages: 7,
      summary: '区分缓存答案与缓存传输算子，并加入 SH PRT 与空间 Transfer Probe。',
    },
    {
      id: 'rcgi',
      number: '08',
      title: 'Radiance Cascades GI',
      file: 'gi_module_rcgi.html',
      group: 'scheme',
      prerequisites: ['foundation'],
      stages: 8,
      summary: '以成熟的 2D interval/merge 实验解释 Radiance Cascades，并标明 3D 边界。',
    },
    {
      id: 'voxelgi',
      number: '09',
      title: 'Voxel GI 教学组装',
      file: 'gi_module_voxel_gi.html',
      group: 'scheme',
      prerequisites: ['voxel', 'cone'],
      stages: 8,
      summary: 'Voxelize → Inject → Mip → Cone Gather → Composite，组装成当前帧 GI。',
    },
    {
      id: 'ddgi',
      number: '10',
      title: 'DDGI teaching-lite 组装',
      file: 'gi_module_ddgi.html',
      group: 'scheme',
      prerequisites: ['sh', 'probes'],
      stages: 10,
      summary: '以 teaching-lite 边界串联 Probe rays、octahedral atlases、distance moments、hysteresis、relocation 与 scrolling。',
    },
    {
      id: 'rendergraph',
      number: '11',
      title: 'RenderGraph GI Workbench',
      file: 'RenderGraph_GI_Lab/index.html',
      group: 'assembly',
      prerequisites: ['rsm', 'voxelgi', 'ddgi', 'prt', 'rcgi'],
      stages: 9,
      summary: '在 D3D12/Vulkan RenderGraph 中连接基础 Pass、切换方案并预览中间资源。',
    },
  ];
  window.GI_LESSONS = Object.freeze(lessons.map((lesson) => Object.freeze({
    ...lesson,
    prerequisites: Object.freeze([...lesson.prerequisites]),
  })));
})();
